// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the bot asks this process to do.
 */
export type Command = { "type": "connect", guildId: string, channelId: string, userId: string, sessionId: string, endpoint: string, token: string, } | { "type": "disconnect", guildId: string, } | { "type": "play", guildId: string, 
/**
 * The cache id, not a path: the sidecar owns the cache layout.
 */
trackId: string, startMs: number, } | { "type": "setNext", guildId: string, trackId: string, } | { "type": "clearNext", guildId: string, } | { "type": "skip", guildId: string, } | { "type": "stop", guildId: string, } | { "type": "pause", guildId: string, } | { "type": "resume", guildId: string, } | { "type": "seek", guildId: string, positionMs: number, } | { "type": "setVolume", guildId: string, gain: number, } | { "type": "setFades", guildId: string, crossfadeMs: number, skipFadeMs: number, } | { "type": "listSessions" } | { "type": "shutdown" };

/**
 * What this process reports back.
 */
export type Event = { "type": "hello", version: number, pid: number, } | { "type": "ready", guildId: string, daveVersion: number, } | { "type": "started", guildId: string, trackId: string, } | { "type": "finished", guildId: string, trackId: string, } | { "type": "starved", guildId: string, trackId: string, } | { "type": "position", guildId: string, trackId: string, positionMs: number, } | { "type": "idle", guildId: string, } | { "type": "reconnecting", guildId: string, reason: string, } | { "type": "disconnected", guildId: string, reason: string, } | { "type": "error", guildId: string | null, message: string, } | { "type": "sessions", guilds: Array<SessionState>, };

/**
 * One guild's state, for a bot that has just restarted and lost its own.
 */
export type SessionState = { guildId: string, channelId: string, trackId: string | null, positionMs: number, paused: boolean, gain: number, };
